#!/usr/bin/env bash
set -e

if [ ! $# -eq 1 ]; then
    TAG='latest'
else
    TAG=$1
fi

# This is very limited:
# - It does not allow for configuring where the database will be
# - It does not allow for other milton.toml locations
# - It does not follow the options in the milton.toml file (related to above)
# However, it works fine with defaults.
docker run -it --rm -v $HOME/.milton:/root/milton/.milton -v $HOME/.config/milton/:/root/.config/milton/ mrhedmad/milton:$TAG

