# Options related to the bot.
bot:
  # >> Token for logging in. The bot will not start if set to null.
  token: null
  # >> The ID of the owner of the bot.
  owner_id: null
  # >> Timeout for listening to pagination instructions (seconds)
  pagination_timeout: 300
  # >> Set the test server. Useful to test some restricted commands.
  test_server_id: null
  # >> Set which extensions are added at startup. The `cli`, `error_handler`
  # and `debug` cogs are already loaded by default.
  startup_extensions: [
    "meta",
    "toys",
    "birthday",
    "rss"
  ]

database:
  # >> Set where the database will be stored.
  path: "~/.milton/database.sqlite"

# >> Set the path for the logs.
# Additional logs are created alongside the main one during runtime.
logs:
  path: "~/.milton/logs/mla.log"
  # Levels can be 50 - CRITICAL, 40 - ERROR, 30 - WARNING, 20 - INFO,
  # 10 - DEBUG or some other int. Log messages of level equal or above the
  # specified will be logged.
  file_level: 20
  stdout_level: 30

# >> Set the bot command prefixes.
prefixes:
  # >> The guild prefix is used for commands sent in a server
  guild:  "$"

# >> Emojis
emojis:
  # Pagination Emojis
  trash: "\u274c"  # :x:
  next:  "\u25b6"  # :arrow_forward:
  back:  "\u25c0"  # :arrow_backward:
  last:  "\u23e9"  # :fast_forward:
  first: "\u23ea"  # :rewind:
  stop:  "\u23f9"  # :stop:

# >> Cog related options
birthday:
  # Time (in UTC hours) when to check for birthdays.
  when: 10
